use std::error::Error;
use std::fmt;

pub fn authenticate() -> Result<(), dyn Error>{
    todo!
    Ok(())
}
